# mapper_params.yaml

laser_scan_matcher:
  odom_frame: "odom"
  base_frame: "base_footprint"
  map_frame: "map"
  use_odom: true
  use_nav_sat: false
  use_landmarks: false
  use_multi_echo_laser_scan: false
  minimum_laser_range: 0.05
  maximum_laser_range: 30.0
  transform_tolerance: 0.3
  search_window: 10.0
  search_grid_resolution: 0.025
  iterations_per_match: 5

async_slam_toolbox:
  map_frame: "map"
  odom_frame: "odom"
  base_frame: "base_footprint"
  fixed_frame: "map"
  enable_cloud_input: false
  use_scan_data: true
  use_multi_echo_laser_scan: false
  use_imu_data: false
  use_odom_data: true
  use_navsat_data: false
  #odom_topic: "/odom"
  scan_topic: "/scan"
  publish_map_odom_transform: true
  publish_free_space: true
  map_update_frequency: 25.0
  map_resolution: 0.05
  map_publish_period_sec: 0.1
  map_update_distance_thresh: 0.05

